[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-cleanhttp"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-hclog"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golangci/golangci-lint"
  version = "1.5.0"

required = ["github.com/golangci/golangci-lint/cmd/golangci-lint"]
